#!/bin/bash

echo "🎨 正在应用 Powerlevel10k 自定义颜色方案"

# 检查配置文件
P10K=~/.p10k.zsh
[[ -f "$P10K" ]] || { echo "❌ 未找到 $P10K"; exit 1; }

# 备份
cp "$P10K" "$P10K.bak.$(date +%Y%m%d_%H%M%S)"
echo "✅ 已备份为 $P10K.bak.$(date +%Y%m%d_%H%M%S)"

# 颜色设置
sed -i '' 's/POWERLEVEL9K_DIR_BACKGROUND=.*/POWERLEVEL9K_DIR_BACKGROUND=6/' "$P10K"
sed -i '' 's/POWERLEVEL9K_DIR_FOREGROUND=.*/POWERLEVEL9K_DIR_FOREGROUND=0/' "$P10K"

sed -i '' 's/POWERLEVEL9K_VCS_CLEAN_BACKGROUND=.*/POWERLEVEL9K_VCS_CLEAN_BACKGROUND=2/' "$P10K"
sed -i '' 's/POWERLEVEL9K_VCS_CLEAN_FOREGROUND=.*/POWERLEVEL9K_VCS_CLEAN_FOREGROUND=0/' "$P10K"

sed -i '' 's/POWERLEVEL9K_ANACONDA_BACKGROUND=.*/POWERLEVEL9K_ANACONDA_BACKGROUND=6/' "$P10K"
sed -i '' 's/POWERLEVEL9K_ANACONDA_FOREGROUND=.*/POWERLEVEL9K_ANACONDA_FOREGROUND=0/' "$P10K"

sed -i '' 's/POWERLEVEL9K_TIME_BACKGROUND=.*/POWERLEVEL9K_TIME_BACKGROUND=7/' "$P10K"
sed -i '' 's/POWERLEVEL9K_TIME_FOREGROUND=.*/POWERLEVEL9K_TIME_FOREGROUND=0/' "$P10K"

sed -i '' 's/POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=.*/POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=3/' "$P10K"
sed -i '' 's/POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=.*/POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=0/' "$P10K"

sed -i '' 's/POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=.*/POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=76/' "$P10K"

# 提示
echo -e "\n✅ 修改完成，请运行：\n  \033[1msource ~/.p10k.zsh\033[0m  应用更改"
